#!/usr/bin/env bash
set -euo pipefail

export GRAMMAR_PATH=grammars

mkdir -p generated
export SILVER_GEN=generated

# Need to bump up the heap space to run the MWDA:
export SVJVM_FLAGS="-Xmx6G -Xss25m"

silver -o foil.jar "$@" edu:umn:cs:melt:foil:host

export GRAMMAR_PATH="foil.jar:$GRAMMAR_PATH"

silver -o composed_host.jar "$@" edu:umn:cs:melt:foil:composed:host
