#!/usr/bin/env bash
set -euo pipefail

export GRAMMAR_PATH=grammars

mkdir -p generated
export SILVER_GEN=generated

# Need to bump up the heap space to run the MWDA:
export SVJVM_FLAGS="-Xmx6G -Xss25m"

# Build host
silver -o foil.jar "$@" edu:umn:cs:melt:foil:host
export GRAMMAR_PATH="foil.jar:$GRAMMAR_PATH"

# Build extensions
silver -o foil-records.jar "$@" edu:umn:cs:melt:foil:extensions:records
export GRAMMAR_PATH="foil-records.jar:$GRAMMAR_PATH"

silver -o foil-complex.jar "$@" edu:umn:cs:melt:foil:extensions:complex
export GRAMMAR_PATH="foil-complex.jar:$GRAMMAR_PATH"

# Build compiler
#silver -o compiler.jar "$@" edu:umn:cs:melt:foil:composed:host
#silver -o compiler.jar "$@" edu:umn:cs:melt:foil:composed:with_records
silver -o compiler.jar "$@" edu:umn:cs:melt:foil:composed:with_all

# Perform MDA tests
#silver --dont-translate "$@" edu:umn:cs:melt:foil:composed:mda_tests
